name:                tuimake
version:             0.1.0.0
github:              "fwcd/tuimake"
license:             GPL-3
author:              "fwcd"
copyright:           "2022 fwcd"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tuimake#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 0.62 && < 1
- deque >= 0.1 && < 1
- parsec >= 3.1 && < 4
- process >= 1.6 && < 2
- text >= 1.2 && < 2
- vty >= 5.33 && < 6

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

executables:
  tuimake:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - tuimake

tests:
  tuimake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tuimake
